@baseUrl = http://localhost:3001
@emailForTesting = admin@ecommerce.com
@passwordForTesting = admin123
@accessToken = {{loginUser.response.body.accessToken}}
@refreshToken = {{loginUser.response.body.refreshToken}}
@emailForTesting2 = user@ecommerce.com
@passwordForTesting2 = user123
@userId = {{registerUser.response.body.id}}
@roomId = {{createRoom.response.body.id}}


### Auth
# @name loginUser
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{emailForTesting}}",
  "password": "{{passwordForTesting}}"
}

### Refresh Token
# @name refreshToken
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### Register New User
# @name registerUser
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "Testando",
  "email": "1{{emailForTesting}}",
  "password": "{{passwordForTesting}}"
}


### Create Room
# @name createRoom
POST {{baseUrl}}/room
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Sala de Teste"
}

### Get All room
# @name getAllroom
GET {{baseUrl}}/room
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get Room by ID
# @name getRoomById
GET {{baseUrl}}/room/{{roomId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Update Room
# @name updateRoom
PUT {{baseUrl}}/room/{{roomId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Sala de Teste Atualizada"
}

### Delete Room
# @name deleteRoom
DELETE {{baseUrl}}/room/{{roomId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
